email: josh@supportdept.io
full_name: Josh Snow
name: Josh
background: Josh is the Owner and lead developer at Support Dept.
timezone: "Australia/Sydney"
schedule_preferences: By default, unless specified otherwise, meetings should be 30 minutes long.
background_preferences: |
  Support Dept specializes in development services. When relevant, Josh may need to loop in team members for specific technical discussions.
response_preferences: |
  Maintain a business casual tone in communications while being professional and direct.
rewrite_preferences: |
  Josh's email communication preferences:
  - Maintain a business casual tone that's professional yet approachable
  - Match the formality level of the sender when appropriate
  - Be direct and clear in responses
  - Include brief greetings and sign-offs for new conversations, can be more direct in ongoing threads
  - Focus on clear, actionable responses
triage_no: |
  - Automated marketing emails and newsletters
  - Mass promotional emails
  - Automated service notifications unless specifically important
  - Generic cold outreach from vendors
  - Spam or obviously automated messages
triage_notify: |
  - Important service notifications that require attention
  - Documents shared that need review or signature
  - Technical inquiries that need personal attention
  - Action items from previous conversations
triage_email: |
  - Direct emails from clients or potential clients
  - Technical discussions requiring Josh's expertise
  - Meeting scheduling requests
  - Direct questions or inquiries about Support Dept services
  - Emails from team members requiring Josh's input
  - Emails from existing business relationships
  - Any emails that appear to be from real people with genuine business inquiries
memory: true
